// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "36c0b5cc-5dc1-46f4-8b5a-6287cb52d4bf";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onIndicationFaultChange();
void onIndicationStarChange();
void onStartChange();
void onStopChange();

float temperatura4;
bool indication_fault;
bool indication_star;
bool start;
bool stop;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temperatura4, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(indication_fault, READWRITE, 1 * SECONDS, onIndicationFaultChange);
  ArduinoCloud.addProperty(indication_star, READWRITE, ON_CHANGE, onIndicationStarChange);
  ArduinoCloud.addProperty(start, READWRITE, ON_CHANGE, onStartChange);
  ArduinoCloud.addProperty(stop, READWRITE, ON_CHANGE, onStopChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
