
#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Tecnelectro"
  https://create.arduino.cc/cloud/things/b61e4fc0-8638-4c7a-90b7-c35268f2c1e1 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float temperatura_grafica;
  bool indication_fault;
  bool indication_start;
  bool start;
  bool stop;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include "Adafruit_MAX31855.h"
#include <Nextion.h>


// Parametros para la funcion thermocouple(MAXCLK, MAXCS, MAXDO);
#define MAXDO   19
#define MAXCLK  18
#define MAXCS   5

// Definicion de pines
#define PIN_EMO 14
#define PIN_LSW 37
#define PIN_TEMPFALLA 38
#define PIN_START 13
#define PIN_PAUSE 36

//#define PIN_OUTPUT 25
#define PIN_PILOTOSTART 27
#define PIN_PILOTOFALLA 12
#define PIN_TURBINA 21

#define PIN_RX 16
#define PIN_TX 17


//Constantes
const unsigned long lectura_temperatura_intervalo = 1000;
const unsigned long lectura_entradas_intervalo = 100;
const unsigned long Start_stop_intervalo = 500;




//Variables
char tempHMI[6];
int estado_EMO = HIGH;
int estado_lsw = HIGH;
int estado_tempFalla = HIGH;
int estado_start = HIGH;
bool temp = false;
unsigned long startTime = 0;    // Tiempo cuando se reanuda
unsigned long elapsedTime = 0;  // Tiempo acumulado total sin incluir pausas
unsigned long tiempoAnterior = 0;
bool enPausa = false;
unsigned long ultimoTiempoActivo = 0;

// Configuración HMI Nextion
HardwareSerial nextionSerial(2);  // Usar UART2 en ESP32 (pines 16-TX, 17-RX)


Adafruit_MAX31855 thermocouple(MAXCLK, MAXCS, MAXDO);

//Configuracion de cada atributo de la HMI
//Se indica la pagina, id, nombre del atributo
NexPage p0 = NexPage(0, 0, "page0");  
NexPage p1 = NexPage(1, 0, "page1");

NexText NexTemperatura = NexText(0, 3, "t0");

NexNumber n0 = NexNumber(0, 1, "n0"); 
NexNumber n1 = NexNumber(0, 12, "n1");
NexNumber n2 = NexNumber(0, 13, "n2");

NexScrolltext NexMensajes = NexScrolltext(0, 5, "g0");

NexText t4 = NexText(0, 7, "t4");
NexWaveform temperatura_grafica_HMI = NexWaveform(1, 1, "s0");

NexTouch *nex_listen_list[] = {
  &n0,
  NULL
};


void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  // 1. Hardware crítico
  analogReadResolution(12);
  nextionSerial.begin(9600, SERIAL_8N1, PIN_RX, PIN_TX);
  nexInit();

  // 2. Termopar
  if (!thermocouple.begin()) {
    Serial.println("ERROR Modulo Temperatura");
    mensajesHMI("ERROR! Modulo Temperatura");
  } else {
    Serial.println("Termopar OK");
  }

  // 3. Configuración de pines
  pinMode(PIN_PILOTOSTART, OUTPUT);
  pinMode(PIN_PILOTOFALLA, OUTPUT);
  pinMode(PIN_TURBINA, OUTPUT);
  pinMode(PIN_START, INPUT);
  pinMode(PIN_EMO, INPUT);
  pinMode(PIN_LSW, INPUT);
  pinMode(PIN_TEMPFALLA, INPUT);
  

  digitalWrite(PIN_PILOTOFALLA, LOW);
  digitalWrite(PIN_PILOTOSTART, LOW);
  digitalWrite(PIN_TURBINA, LOW);
  digitalWrite(PIN_PAUSE, HIGH);

  Serial.println("******************************************************************************");
  delay(1000);
}


void loop() {
  ArduinoCloud.update();
  actualTemperatura();
  //Corriente();
  //acciones();
  //erroresTemperatura();
  lecturaEntradas();
  graficas();
  //onIndicationStarChange();
  encender();
  //notificaciones();

  yield();
  delay(10);
}

/*
  Since Start is READ_WRITE variable, onStartChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onStartChange()  {
  static unsigned long lastReadTime = 0;
  unsigned long currentTime = millis();
  
  if (currentTime - lastReadTime >= Start_stop_intervalo) {
    lastReadTime = currentTime;

    digitalWrite(PIN_PILOTOSTART, HIGH);
    digitalWrite(PIN_TURBINA, HIGH);
    indication_start = true;
    temp = true;
    //digitalWrite(PIN_PAUSE, HIGH);
    //tiempo();
  }
}

/*
  Since Stop is READ_WRITE variable, onStopChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onStopChange()  {
  static unsigned long lastReadTime = 0;
  unsigned long currentTime = millis();
  
  if (currentTime - lastReadTime >= Start_stop_intervalo) {
    lastReadTime = currentTime;

    digitalWrite(PIN_PILOTOSTART, LOW);
    digitalWrite(PIN_TURBINA, LOW);
    //digitalWrite(PIN_PAUSE, HIGH);
    indication_start = false;
    temp = false;
  }
  
}

void actualTemperatura(){
  static unsigned long lastReadTime = 0;
  unsigned long currentTime = millis();
  
  // Leer cada segundo
  if (currentTime - lastReadTime >= lectura_temperatura_intervalo) {
    lastReadTime = currentTime;
    
    // Leer temperatura en Celsius
    double tempC = thermocouple.readCelsius();
    
    // Verificar si la lectura es válida
    if (isnan(tempC)) {
      Serial.println("Error en la lectura del termopar");
      mensajesHMI("Error termopar");
      //verificarErrores();
    } else {
      // Mostrar temperatura en consola
      temperatura_grafica = tempC;
      Serial.print("Temperatura: ");
      Serial.print(tempC);
      Serial.println(" °C");
      
      // Mostrar temperatura en HMI
      //mensajesHMI("Termopar OK");
      mostrarTemperaturaHMI(tempC);
    }
  }
}

// Función para mostrar temperatura (t0) en HMI
void mostrarTemperaturaHMI(double temperatura) {
  // Formatear el valor con 1 decimal
  String tempStr = String(temperatura, 1);
  tempStr.toCharArray(tempHMI, 6);
  NexTemperatura.setText(tempHMI);
}

// Función para mostrar mensajes en el campo de texto principal (g0) del HMI
void mensajesHMI(String mensaje) {
  char bufferMensaje[50];
  mensaje.toCharArray(bufferMensaje, 50);
  NexMensajes.setText(bufferMensaje);
}

//Solamente lee el estado de las entrdas
void lecturaEntradas() {
  static unsigned long lastReadTime = 0;
  unsigned long currentTime = millis();

  char mensaje[50];

  // Leer cada segundo
  if (currentTime - lastReadTime >= lectura_entradas_intervalo) {
    lastReadTime = currentTime;

    // Leer entradas
    estado_EMO = digitalRead(PIN_EMO);
    estado_lsw = digitalRead(PIN_LSW);
    estado_tempFalla = digitalRead(PIN_TEMPFALLA);
    
    mensaje[0] = '\0';
    
    digitalWrite(PIN_PILOTOFALLA, LOW);
    indication_fault = false;

    if (estado_EMO == HIGH || estado_lsw == HIGH || estado_tempFalla == HIGH) {
        //estado_start = LOW;
        //indication_fault = false;
        //digitalWrite(PIN_PILOTOFALLA, HIGH);

        
        if(estado_EMO == LOW){
          snprintf(mensaje, sizeof(mensaje),
            "(EMO) Paro de emergencia");
            digitalWrite(PIN_PILOTOSTART, LOW);
            digitalWrite(PIN_TURBINA, LOW);
            digitalWrite(PIN_PILOTOFALLA, HIGH);
            //digitalWrite(PIN_PAUSE, LOW);
            indication_fault = true;
            indication_start = false;
            temp = false;   
        }
        

        if(estado_lsw == LOW){
          snprintf(mensaje, sizeof(mensaje),
            "(LSW) Puerta abierta");
            digitalWrite(PIN_PILOTOSTART, LOW);
            digitalWrite(PIN_TURBINA, LOW);
            digitalWrite(PIN_PILOTOFALLA, HIGH);
            //digitalWrite(PIN_PAUSE, LOW);
            indication_fault = true;
            indication_start = false;
            temp = false;
        }

        if(estado_tempFalla == LOW){
          snprintf(mensaje, sizeof(mensaje),
            "Fallo de temperatura");
            digitalWrite(PIN_PILOTOSTART, LOW);
            digitalWrite(PIN_TURBINA, LOW);
            digitalWrite(PIN_PILOTOFALLA, HIGH);
            //digitalWrite(PIN_PAUSE, LOW);
            indication_fault = true;
            indication_start = false;
            temp = false;
        }

        // Mostrar en HMI
        mensajesHMI(mensaje);
    }
    
    
  }
}

//se grafican las variables en HMI
void graficas() {
  static unsigned long lastReadTime = 0;
  unsigned long currentTime = millis();
  
  // Leer cada segundo
  if (currentTime - lastReadTime >= lectura_temperatura_intervalo) {
    lastReadTime = currentTime;
    
    // Leer temperatura en Celsius
    double tempC = thermocouple.readCelsius();
    
    // Verificar si la lectura es válida
    if (isnan(tempC)) {
      Serial.println("Error en la lectura del termopar");
      //mensajesHMI("Error termopar");
      //verificarErrores();
    } else {
      temperatura_grafica_HMI.addValue(0, tempC);  //el primer dato indica el canal, el componente permite 4 canales, pero en la programacion el canal 1 sería el 0 en el ESP32
  
    }

    ///////////// GRAFICAR LA CORRIENTE /////////////

  }
}

void encender() {
  estado_start = digitalRead(PIN_START);

  if (estado_start == LOW) {
    digitalWrite(PIN_PILOTOSTART, HIGH);
    digitalWrite(PIN_TURBINA, HIGH);
    indication_start = true;
    temp = true;
  } 
  if (temp) {
  tiempo();
  }    
}

void tiempo() {
  Serial.println("ENTRA A TIEMPO");
  // Leer el estado del botón de pausa
  /*
  if (digitalRead(PIN_PAUSE) == LOW) {
    delay(50);  // Debounce
    if (digitalRead(PIN_PAUSE) == LOW) {
      startTime = elapsedTime;  // Guardar el tiempo actual al pausar
    }
    while (digitalRead(PIN_PAUSE) == LOW) {
      delay(10);  // Esperar hasta que se suelte el botón
    }
    elapsedTime = startTime;
  }
  */

  // Si no está en pausa, actualizar el tiempo acumulado
    if (millis() - tiempoAnterior > 1000) {
      Serial.println("ENTRA AL CONDICIONAL");
      elapsedTime = elapsedTime + 1;  // Incrementar en 1 segundo
      tiempoAnterior = millis();

      // Convertir el tiempo acumulado a horas, minutos y segundos
      unsigned long totalSeconds = elapsedTime;
      int hours = totalSeconds / 3600;
      int minutes = (totalSeconds % 3600) / 60;
      int seconds = totalSeconds % 60;

      //Mostrar numeros en HMI
      n1.setValue(hours);
      n2.setValue(minutes);
      //Mostrar el tiempo acumulado en formato hh : mm : ss
      Serial.print("Tiempo acumulado: ");
      if (hours < 10) Serial.print("0");
      // Serial.print(hours);
      //Serial.print(":");
      if (minutes < 10) Serial.print("0");
      Serial.print(minutes);
      Serial.print(":");
      if (seconds < 10) Serial.print("0");
      Serial.println(seconds);
    }

  
}

