// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "1597038e-fe23-4e8a-8d03-0a1e24852ec9";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onStartChange();
void onStopChange();

float temperatura4;
bool indication_fault;
bool indication_start;
bool start;
bool stop;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(temperatura4, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(indication_fault, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(indication_start, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(start, READWRITE, ON_CHANGE, onStartChange);
  ArduinoCloud.addProperty(stop, READWRITE, ON_CHANGE, onStopChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
